### ISSUE TITLE
Where do non-MongoDB modules go?

### ISSUE THREAD

**Issue by rueckstiess** [mongodb-js/mongodb-js.github.io#16]
Say we want to offer automated installation of sublime plugins for new contributors via `mj`. It would be nice if that was its own npm module, e.g. `sublime-pkg-installer`.

That has nothing to do with MongoDB though. Does it still go in this org? Because `mj` depends on it? 

What are alternatives? Host privately?

**Comment by imlucas** [comment]
My feeling is all JS modules should go into the org because of our goals (shared responsibility, discoverability, etc).  All modules should conform to our quality guidelines (see #8) and we should make it as easy as possible to take an existing repo -> run a command on it -> fix what we can automatically/provide your with a list of todo's.

Thoughts?

**Comment by imlucas** [comment]
Answered: https://github.com/mongodb-js/mongodb-js.github.io/blob/dev/docs/transferring.md#what-projects-can-be-transferred
